  FROM n8nio/runners:2.6.4
  USER root
  RUN uv pip install --python /opt/runners/task-runner-python/.venv/bin/python pdfminer.six
  RUN sed -i 's/"N8N_RUNNERS_STDLIB_ALLOW": ""/"N8N_RUNNERS_STDLIB_ALLOW": "*"/' /etc/n8n-task-runners.json && \
      sed -i 's/"N8N_RUNNERS_EXTERNAL_ALLOW": ""/"N8N_RUNNERS_EXTERNAL_ALLOW": "pdfminer"/' /etc/n8n-task-runners.json
  USER runner